name: new_horizen_test_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  # Network
  dio: ^5.3.2
  internet_connection_checker: ^1.0.0+1
  # Local Storage
  shared_preferences: ^2.2.1
  # Core Utils
  equatable: ^2.0.5
  get_it: ^7.6.4
  dartz: ^0.10.1
  # UI
  shimmer: ^3.0.0
  flutter_svg: ^2.0.17
  lottie: ^3.1.3
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.1
  mockito: ^5.3.2


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/icons/
    - assets/fonts/
    - assets/gifs/
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-SemiBold.ttf
          weight: 600
